# action.yml
name: 'GCR Cleaner Action'
description: 'Clean GCR and Artifact Registry images'
inputs:
  repository-id:  # id of input
    description: 'Name of the repository to clean'
    required: true
  keep:
    description: 'Total images to keep'
    required: false
outputs:
  total: # id of output
    description: 'total'
runs:
  using: 'docker'
  image: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli:latest'
  args:
    - -repo=${{ inputs.repository-id }}
    - -keep=${{ inputs.keep }}